### ISSUE TITLE
A error happened when installing stylus

### ISSUE THREAD

**Issue by frontoldman** [vuejs/vue-hackernews-2.0#12]
at CachedPathEvaluator.visitImport (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus-loader/lib/evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus/lib/renderer.js:86:26)
    at /Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/stylus-loader/index.js:158:12
    at tryCatchReject (/Users/zhangran/Documents/git-test/vue-hackernews-2.0/node_modules/when/lib/makePromise.js:840:30)

**Comment by yyx990803** [comment]
Make sure to use latest Node/npm.
