### ISSUE TITLE
Get error at after npm install. (but yarn install working)

### ISSUE THREAD

**Issue by 2t10p** [vuejs/vue-hackernews-2.0#120]
hi ~ 

i am trying set up this app to learn vue.js,
and got a probleam.

after npm install and run up service,
only get 500 error at index page.
[but yran install was fine]

here is the log, hope can find something.
```
$ nvm list
->       v6.9.4
         system
default -> lts/boron (-> v6.9.4)
node -> stable (-> v6.9.4) (default)
stable -> 6.9 (-> v6.9.4) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> v6.9.4)
lts/argon -> v4.7.2 (-> N/A)
lts/boron -> v6.9.4

$ npm -v
3.10.10

$ npm run dev

> vue-hackernews-2.0@ dev /web-vue-hackernews-2.0
> node server

server started at localhost:8080
webpack built 148eebe5d6a79ce0699c in 3499ms
Hash: 148eebe5d6a79ce0699c
Version: webpack 2.2.0-rc.7
Time: 3499ms
        Asset       Size  Chunks                    Chunk Names
       app.js     166 kB       0  [emitted]         app
    vendor.js     431 kB       1  [emitted]  [big]  vendor
   app.js.map     209 kB       0  [emitted]         app
vendor.js.map     534 kB       1  [emitted]         vendor
   index.html  614 bytes          [emitted]

WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.

Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0
webpack: bundle is now VALID.
data pre-fetch: 2029ms
[Vue warn]: Error when rendering component <transition>:
error during render : /top/
TypeError: child.key.indexOf is not a function
    at Proxy.render (/web-vue-hackernews-2.0/node_modules/vue/dist/vue.runtime.common.js:5954:19)
    at VueComponent.Vue._render (/web-vue-hackernews-2.0/node_modules/vue/dist/vue.runtime.common.js:2216:22)
    at renderComponent (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6078:25)
    at renderNode (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6061:7)
    at next (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6197:9)
    at Object.cachedWrite [as write] (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at next (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6199:17)
    at next (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6189:7)
    at Object.cachedWrite [as write] (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at next (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6199:17)
    at cachedWrite (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at renderNode (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6069:7)
    at next (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6197:9)
    at cachedWrite (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at renderElement (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6121:5)
    at renderNode (/web-vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6065:7)
```

**Comment by wangfuda** [comment]
yeah, i gotta the same problem,who have resolve it?

**Comment by wangfuda** [comment]
i gotta the solution.
just find the code cause this problem in the file[/web-vue-hackernews-2.0/node_modules/vue/dist/vue.runtime.common.js:5954], and modify a little like this:
`: child.key**.toString()**.indexOf(id) === 0 ? child.key : id + child.key;`

**Comment by yyx990803** [comment]
Sorry, this is a bug in Vue 2.1.9, will be fixed soon.
