### ISSUE TITLE
Error running this project in dev

### ISSUE THREAD

**Issue by stran12** [vuejs/vue-hackernews-2.0#152]
```
vue-hackernews-2.0 · (master) ⟩ yarn run dev                                                                                        ~/g/vue-hackernews-2.0
yarn run v0.21.3
$ node server 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (/Users/stran/git/vue-hackernews-2.0/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/stran/git/vue-hackernews-2.0/server.js:83:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm trying to use this repo as a baseline and trim it down to just vue + vue-router + vue-ssr + preFetch. @yyx990803  Do you a starter template with one component, vue-router, server-side render with a preFetch data call? 

Love the work that you and your team have been doing. Keep up the great outstanding work. Thanks in advance!

**Comment by yyx990803** [comment]
You have something else using port 8080.

**Comment by stran12** [comment]
@yyx990803 Wow! That was a quick response. Thanks!
