### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by john-ko** [vuejs/vue-hackernews-2.0#158]
# steps to reproduce
`git clone git@github.com:vuejs/vue-hackernews-2.0.git`
`cd vue-hackernews-2.0/`
`npm install`
`npm run dev`

# error 
```
> vue-hackernews-2.0@ dev /Users/john-ko/projects/test/vue-hackernews-2.0
> node server

server started at localhost:8080


 ERROR  Failed to compile with 1 errors                                                                                             12:15:56 PM

 error  in ./src/entry-server.js

Module parse failed: /Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/buble-loader/index.js??ref--1!/Users/john-ko/projects/test/vue-hackernews-2.0/src/entry-server.js Cannot read property 'name' of null
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'name' of null
    at Parser.walkFunctionDeclaration (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:539:39)
    at Parser.walkStatement (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:436:32)
    at Parser.walkExportDefaultDeclaration (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:613:9)
    at Parser.walkStatement (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:436:32)
    at Parser.walkStatements (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:419:9)
    at Parser.parse (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/Parser.js:1193:8)
    at doBuild.e (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/NormalModule.js:288:17)
    at runLoaders (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/webpack/lib/NormalModule.js:206:11)
    at /Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.BubleLoader (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/buble-loader/index.js:48:10)
    at LOADER_EXECUTION (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/john-ko/projects/test/vue-hackernews-2.0/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
```

# my workaround
I changed https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L10
`entry-server.js` line 10 from
`export default context => {`
to 
`export default function entryServer (context) {`

has anyone else received that error?

node - v.7.8.0

**Comment by john-ko** [comment]
figured out the issue, unrelated
