### ISSUE TITLE
求教：无法在app.js引用全局样式

### ISSUE THREAD

**Issue by zhump** [vuejs/vue-hackernews-2.0#167]
app.js

```
import Vue from 'vue'
import App from './App.vue'
import store from './store'
import router from './router'
import './aa.css'
```

控制台错误信息：
```
ReferenceError: window is not defined
    at server-bundle.js:1026:10
    at server-bundle.js:1016:47
    at module.exports.module.exports (~/style-loader/addStyles.js:47:0)
    at Object.module.exports.module.exports (~/element-ui/lib/theme-default/index.css?1240:7:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 57f2cc31b3dad0c6060b:25:0)
    at Object.module.exports.module.exports.rawScriptExports (server-bundle.js:193:97)
    at __webpack_require__ (webpack:/webpack/bootstrap 57f2cc31b3dad0c6060b:25:0)
    at Object.<anonymous> (server-bundle.js:488:63)
    at __webpack_require__ (webpack:/webpack/bootstrap 57f2cc31b3dad0c6060b:25:0)
    at server-bundle.js:95:18
```

请问，我该怎么引用全局的样式文件，谢谢！

**Comment by zhump** [comment]
哈哈 刚提问，就找到解决方法了，，
```
{
            test: /\.css$/,   
            loader: ["vue-style-loader", "css-loader"]
        }

```

**Comment by JounQin** [comment]
把 css 最终也交给 vue-style-loader 而不是 style-loader 处理就好了，如果最终需要把全局 css 抽成单独的文件的话注意生产环境把此 css 在服务端排除（使用 null-loader之类的），可以看下 https://github.com/JounQin/vue-ssr/，我们有两个全局的 css，一个 bootstrap 一个 app。

**Comment by zhump** [comment]
JounQin  thank you ！
