### ISSUE TITLE
Error when updating to Vue 2.4.1

### ISSUE THREAD

**Issue by MDSLKTR** [vuejs/vue-hackernews-2.0#227]
When trying to access the site i get the following error on render:

```
error during render : /
RangeError: Maximum call stack size exceeded
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1082:20)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
    at mergeData (/Users/mdslktr/Projects/px-secrets/node_modules/vue/dist/vue.runtime.common.js:1093:7)
````
This happens since the 2.4.1 Update of Vue. Does this Project need updating with the out of the box changes for SSR in Vue?

Regards,
Simon

**Comment by MDSLKTR** [comment]
Closed as this issue relates to the latest webpack release.
