### ISSUE TITLE
Error on Deploying to heroku

### ISSUE THREAD

**Issue by webgururobin** [vuejs/vue-hackernews-2.0#233]
I am trying to deploy the app on heroku following https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction but it is not working, ( it works completely fine on now.sh )

when I ran heroku logs --tail

**the error is rimraf: not found**

I tried to fix it by globally installing rimraf on heroku

`heroku run npm install rimraf -g`

but that doesn't seem to work either.

are there any additional steps to following while deploying it to heroku?

**Comment by nasyrov** [comment]
@webgururobin make sure you install your dev dependencies on Heroku, by default it's disabled

see https://devcenter.heroku.com/articles/nodejs-support#devdependencies

**Comment by valentinvieriu** [comment]
can you check first https://github.com/vuejs/vue-hackernews-2.0/issues/224

**Comment by newenegue** [comment]
I think the issue here is when `NODE_ENV=production`, then it will only `npm install` the `dependencies` NOT the `devDependencies`

In this case, `rimraf` is included under `devDependencies`.  

I've moved `rimraf` to `dependencies` and now have the following error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! within@1.0.0 build:client: `cross-env NODE_ENV=${NODE_ENV:=development} webpack --config build/webpack.client.config.js --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the within@1.0.0 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-01-24T19_52_19_701Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! within@1.0.0 build: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the within@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-01-24T19_52_19_732Z-debug.log
```

Does anyone have ideas on what is causing the error or have any ideas for a solution?
