### ISSUE TITLE
npm start  (Error: Cannot find module './dist/vue-ssr-server-bundle.json')

### ISSUE THREAD

**Issue by badis** [vuejs/vue-hackernews-2.0#255]
I have cloned this repo.
Executed: 
```
npm install 
npm start
```
I got this error: 

```
> vue-hackernews-2.0@ start /home/badis/Desktop/vue-hackernews-2.0
> cross-env NODE_ENV=production node server

module.js:529
    throw err;
    ^

Error: Cannot find module './dist/vue-ssr-server-bundle.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/badis/Desktop/vue-hackernews-2.0/server.js:42:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by john-ko** [comment]
```
npm install
npm run build
npm start
```

for production like mode

for dev.. run `npm run dev`

**Comment by badis** [comment]
That's solved my issue. thanks !
