### ISSUE TITLE
when I set NODE_ENV =='development',it throw error

### ISSUE THREAD

**Issue by hiBruce** [vuejs/vue-hackernews-2.0#359]
In development,I set NODE_ENV=='development',and then throw error.

![image](https://user-images.githubusercontent.com/39815835/54268885-2e527b80-45b7-11e9-8493-c495b0c55f69.png)

here is error detail:
"ReferenceError: development is not defined
    at Object.<anonymous> (server-bundle.js:998:13)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.module.exports.__webpack_exports__.a (server-bundle.js:227:14)
    at __webpack_require__ (server-bundle.js:27:30)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (E:\work\vue-ssr-new\node_modules\vue-server-renderer\build.dev.js:9274:21)
    at E:\work\vue-ssr-new\node_modules\vue-server-renderer\build.dev.js:9332:18
    at new Promise (<anonymous>)
    at E:\work\vue-ssr-new\node_modules\vue-server-renderer\build.dev.js:9324:14
    at Object.renderToString (E:\work\vue-ssr-new\node_modules\vue-server-renderer\build.dev.js:9500:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)"

more detail:
 node:8.11.2

**Comment by hiBruce** [comment]
I set default env,now vue Devtools not work.

**Comment by hiBruce** [comment]
![image](https://user-images.githubusercontent.com/39815835/54275419-83958980-45c5-11e9-9b4a-30133837362a.png)
write like this,it's ok.
please colse this issue,thanks.
