### ISSUE TITLE
npm run dev 编译成功 但是访问链接后奔溃

### ISSUE THREAD

**Issue by yjj5855** [vuejs/vue-hackernews-2.0#36]
vue-router 服务端渲染的时候报错

> node server

server started at localhost:8080
webpack built 305ac7407cc71ca06b31 in 6405ms
Hash: 305ac7407cc71ca06b31
Version: webpack 2.1.0-beta.25
Time: 6405ms
                      Asset    Size  Chunks             Chunk Names
           client-bundle.js  160 kB       0  [emitted]  app
    client-vendor-bundle.js  442 kB       1  [emitted]  vendor
       client-bundle.js.map  207 kB       0  [emitted]  app
client-vendor-bundle.js.map  549 kB       1  [emitted]  vendor
webpack: bundle is now VALID.
/Users/yangjiajun/vue-hackernews-2.0/server.js:85
    throw err
    ^

TypeError: this$1.ensureURL is not a function
    at /Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1227:12
    at /Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1279:9
    at step (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1191:7)
    at step (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1198:9)
    at runQueue (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1202:3)
    at /Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1276:5
    at step (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1191:7)
    at step (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1198:9)
    at step (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1198:9)
    at runQueue (/Users/yangjiajun/vue-hackernews-2.0/node_modules/vue-router/dist/vue-router.js:1202:3)

**Comment by YouthLab** [comment]
+1
我也遇到同样问题 @yyx990803

**Comment by isairz** [comment]
https://github.com/vuejs/vue-router/issues/698

Fixed at vue-router@2.0.0-rc7

**Comment by yjj5855** [comment]
@isairz 3Q
