### ISSUE TITLE
vue-hn.now.sh - 502 An error occured with your deployment.

### ISSUE THREAD

**Issue by limonte** [vuejs/vue-hackernews-2.0#39]
![](https://i.imgur.com/b1wOfEE.png)

<details> 
  <summary>Logs:</summary>

```
10/02/16 1:57:20 PM
whole request: 14ms
10/02/16 1:57:20 PM
whole request: 15ms
10/02/16 1:57:21 PM
whole request: 12ms
10/02/16 1:57:55 PM
whole request: 69ms
10/02/16 1:59:02 PM
whole request: 18ms
10/02/16 2:01:08 PM
whole request: 17ms
10/02/16 2:01:23 PM
whole request: 16ms
10/02/16 2:01:27 PM
whole request: 18ms
10/02/16 2:01:28 PM
whole request: 19ms
10/02/16 2:02:49 PM
whole request: 54ms
10/02/16 2:03:52 PM
whole request: 87ms
10/02/16 2:06:17 PM
whole request: 11ms
10/02/16 2:06:21 PM
whole request: 21ms
10/02/16 2:06:37 PM
whole request: 18ms
10/02/16 2:07:09 PM
whole request: 98ms
10/02/16 2:07:33 PM
whole request: 16ms
10/02/16 2:08:13 PM
whole request: 76ms
10/02/16 2:09:17 PM
whole request: 14ms
10/02/16 2:10:22 PM
whole request: 74ms
10/02/16 2:11:21 PM
whole request: 54ms
10/02/16 2:11:32 PM
whole request: 16ms
10/02/16 2:11:36 PM
whole request: 11ms
10/02/16 2:12:09 PM
whole request: 55ms
10/02/16 2:12:14 PM
whole request: 11ms
10/02/16 2:12:34 PM
whole request: 54ms
10/02/16 2:13:46 PM
whole request: 13ms
10/02/16 2:13:54 PM
whole request: 164ms
10/02/16 2:15:52 PM
whole request: 30ms
10/02/16 2:17:37 PM
whole request: 68ms
10/02/16 2:19:51 PM
whole request: 95ms
10/02/16 2:21:17 PM
whole request: 27ms
10/02/16 2:21:33 PM
whole request: 18ms
10/02/16 2:21:49 PM
whole request: 18ms
10/02/16 2:22:13 PM
whole request: 87ms
10/02/16 2:22:18 PM
whole request: 94ms
10/02/16 2:22:20 PM
whole request: 13ms
10/02/16 2:22:22 PM
whole request: 16ms
10/02/16 2:22:26 PM
whole request: 17ms
10/02/16 2:22:48 PM
whole request: 22ms
10/02/16 2:22:51 PM
whole request: 14ms
10/02/16 2:22:55 PM
whole request: 11ms
10/02/16 2:23:07 PM
whole request: 9ms
10/02/16 2:23:21 PM
whole request: 19ms
10/02/16 2:23:46 PM
whole request: 13ms
10/02/16 2:23:55 PM
whole request: 13ms
10/02/16 2:24:00 PM
whole request: 17ms
10/02/16 2:24:07 PM
whole request: 14ms
10/02/16 2:24:33 PM
whole request: 13ms
10/02/16 2:25:06 PM
whole request: 14ms
10/02/16 2:27:44 PM
whole request: 57ms
10/02/16 2:27:56 PM
whole request: 13ms
10/02/16 2:27:59 PM
whole request: 22ms
10/02/16 2:28:14 PM
whole request: 52ms
10/02/16 2:30:50 PM
whole request: 53ms
10/02/16 2:31:03 PM
whole request: 87ms
10/02/16 2:31:46 PM
whole request: 12ms
10/02/16 2:32:50 PM
whole request: 11ms
10/02/16 2:33:17 PM
whole request: 53ms
10/02/16 2:34:48 PM
whole request: 51ms
10/02/16 2:36:19 PM
whole request: 78ms
10/02/16 2:36:33 PM
whole request: 13ms
10/02/16 2:37:06 PM
whole request: 18ms
10/02/16 2:37:18 PM
whole request: 19ms
10/02/16 2:37:18 PM
whole request: 12ms
10/02/16 2:38:47 PM
whole request: 14ms
10/02/16 2:38:52 PM
whole request: 62ms
10/02/16 2:38:57 PM
whole request: 110ms
10/02/16 2:39:02 PM
whole request: 85ms
10/02/16 2:39:14 PM
whole request: 18ms
10/02/16 2:44:11 PM
whole request: 70ms
10/02/16 2:44:23 PM
whole request: 17ms
10/02/16 2:44:39 PM
whole request: 13ms
10/02/16 2:44:55 PM
whole request: 15ms
10/02/16 2:45:32 PM
whole request: 24ms
10/02/16 2:47:04 PM
whole request: 59ms
10/02/16 2:47:55 PM
whole request: 13ms
10/02/16 2:50:16 PM
whole request: 49ms
10/02/16 2:51:53 PM
whole request: 89ms
10/02/16 2:51:55 PM
whole request: 12ms
10/02/16 2:51:58 PM
whole request: 18ms
10/02/16 2:52:09 PM
whole request: 16ms
10/02/16 2:52:11 PM
whole request: 81ms
10/02/16 2:52:26 PM
whole request: 91ms
10/02/16 2:53:05 PM
whole request: 12ms
10/02/16 2:55:08 PM
whole request: 19ms
10/02/16 2:55:34 PM
whole request: 11ms
10/02/16 2:55:49 PM
whole request: 11ms
10/02/16 2:56:05 PM
whole request: 12ms
10/02/16 2:56:53 PM
whole request: 49ms
10/02/16 2:56:58 PM
whole request: 52ms
10/02/16 2:57:07 PM
whole request: 18ms
10/02/16 2:57:13 PM
whole request: 22ms
10/02/16 2:57:17 PM
whole request: 14ms
10/02/16 2:57:23 PM
whole request: 53ms
10/02/16 2:57:58 PM
whole request: 113ms
10/02/16 2:58:13 PM
whole request: 21ms
10/02/16 2:58:52 PM
whole request: 13ms
10/02/16 2:59:05 PM
whole request: 20ms
10/02/16 2:59:12 PM
whole request: 69ms
10/02/16 2:59:21 PM
whole request: 13ms
10/02/16 2:59:23 PM
whole request: 19ms
10/02/16 2:59:50 PM
whole request: 12ms
10/02/16 3:00:44 PM
whole request: 56ms
10/02/16 3:00:46 PM
whole request: 16ms
10/02/16 3:05:01 PM
whole request: 13ms
10/02/16 3:05:38 PM
whole request: 56ms
10/02/16 3:06:17 PM
whole request: 14ms
10/02/16 3:06:45 PM
whole request: 15ms
10/02/16 3:07:22 PM
whole request: 75ms
10/02/16 3:07:36 PM
whole request: 12ms
10/02/16 3:09:51 PM
whole request: 60ms
10/02/16 3:09:59 PM
whole request: 22ms
10/02/16 3:10:09 PM
whole request: 20ms
10/02/16 3:13:12 PM
whole request: 12ms
10/02/16 3:14:11 PM
whole request: 13ms
10/02/16 3:15:34 PM
whole request: 62ms
10/02/16 3:15:54 PM
whole request: 52ms
10/02/16 3:16:28 PM
whole request: 82ms
10/02/16 3:17:55 PM
whole request: 11ms
10/02/16 3:17:57 PM
whole request: 112ms
10/02/16 3:17:57 PM
whole request: 17ms
10/02/16 3:17:59 PM
whole request: 22ms
10/02/16 3:18:01 PM
whole request: 14ms
10/02/16 3:18:03 PM
whole request: 118ms
10/02/16 3:18:06 PM
whole request: 85ms
10/02/16 3:18:10 PM
whole request: 11ms
10/02/16 3:18:32 PM
whole request: 19ms
10/02/16 3:21:05 PM
whole request: 19ms
10/02/16 3:21:22 PM
whole request: 60ms
10/02/16 3:22:35 PM
whole request: 79ms
10/02/16 3:24:37 PM
whole request: 11ms
10/02/16 3:24:56 PM
whole request: 15ms
10/02/16 3:26:49 PM
whole request: 19ms
10/02/16 3:27:10 PM
whole request: 18ms
10/02/16 3:27:13 PM
whole request: 11ms
10/02/16 3:27:14 PM
whole request: 53ms
10/02/16 3:27:33 PM
whole request: 31ms
10/02/16 3:31:58 PM
whole request: 74ms
10/02/16 3:32:02 PM
whole request: 79ms
10/02/16 3:32:18 PM
whole request: 17ms
10/02/16 3:32:25 PM
whole request: 12ms
10/02/16 3:32:26 PM
whole request: 10ms
10/02/16 3:32:28 PM
whole request: 105ms
10/02/16 3:33:22 PM
whole request: 11ms
10/02/16 3:35:14 PM
whole request: 58ms
10/02/16 3:35:21 PM
whole request: 13ms
10/02/16 3:35:27 PM
whole request: 106ms
10/02/16 3:35:31 PM
whole request: 82ms
10/02/16 3:35:32 PM
whole request: 11ms
10/02/16 3:35:46 PM
whole request: 110ms
10/02/16 3:35:54 PM
whole request: 14ms
10/02/16 3:36:07 PM
whole request: 17ms
10/02/16 3:36:09 PM
whole request: 16ms
10/02/16 3:36:12 PM
whole request: 14ms
10/02/16 3:36:20 PM
whole request: 111ms
10/02/16 3:36:47 PM
whole request: 53ms
10/02/16 3:37:25 PM
whole request: 11ms
10/02/16 3:37:25 PM
whole request: 12ms
10/02/16 3:37:32 PM
whole request: 12ms
10/02/16 3:38:29 PM
whole request: 72ms
10/02/16 3:39:56 PM
whole request: 11ms
10/02/16 3:40:27 PM
whole request: 18ms
10/02/16 3:40:29 PM
whole request: 16ms
10/02/16 3:40:42 PM
whole request: 20ms
10/02/16 3:40:59 PM
whole request: 23ms
10/02/16 3:42:23 PM
whole request: 15ms
10/02/16 3:42:41 PM
whole request: 52ms
10/02/16 3:43:12 PM
whole request: 12ms
10/02/16 3:49:23 PM
whole request: 57ms
10/02/16 3:52:23 PM
whole request: 61ms
10/02/16 3:53:08 PM
whole request: 15ms
10/02/16 3:55:26 PM
whole request: 83ms
10/02/16 3:55:35 PM
whole request: 24ms
10/02/16 3:56:51 PM
whole request: 28ms
10/02/16 3:57:29 PM
whole request: 87ms
10/02/16 3:57:51 PM
whole request: 13ms
10/02/16 4:07:25 PM
whole request: 71ms
10/02/16 4:08:07 PM
whole request: 18ms
10/02/16 4:10:14 PM
whole request: 54ms
10/02/16 4:11:11 PM
whole request: 56ms
10/02/16 4:11:18 PM
whole request: 79ms
10/02/16 4:12:19 PM
whole request: 18ms
10/02/16 4:16:25 PM
whole request: 10ms
10/02/16 4:16:25 PM
whole request: 16ms
10/02/16 4:17:07 PM
whole request: 11ms
10/02/16 4:17:12 PM
whole request: 12ms
10/02/16 4:17:28 PM
whole request: 10ms
10/02/16 4:20:42 PM
whole request: 55ms
10/02/16 4:21:58 PM
whole request: 52ms
10/02/16 4:22:01 PM
whole request: 62ms
10/02/16 4:22:03 PM
whole request: 70ms
10/02/16 4:29:09 PM
whole request: 95ms
10/02/16 4:34:50 PM
whole request: 14ms
10/02/16 4:35:05 PM
whole request: 17ms
10/02/16 4:35:34 PM
whole request: 12ms
10/02/16 4:36:05 PM
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot set property '__lastUpdated' of null
    at __vue_ssr_bundle__:163:27
    at c (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:240:58)
    at /home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:201:710
    at ec (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:52:165)
    at ac (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:31:216)
    at bc (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:30:1259)
    at Object.I (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:218:393)
    at /home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:181:3
    at Rh.h.Jd (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:186:104)
    at Fh.Jd (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:176:364)
    at wh.Jg (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:174:280) 
10/02/16 4:36:05 PM

/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:52
(d="0"+d),c+=d;return c.toLowerCase()}var zd=/^-?\d{1,10}$/;function td(a){return zd.test(a)&&(a=Number(a),-2147483648<=a&&2147483647>=a)?a:null}function ec(a){try{a()}catch(b){setTimeout(function(){R("Exception was thrown by user callback.",b.stack||"");throw b;},Math.floor(0))}}function S(a,b){if(t(a)){var c=Array.prototype.slice.call(arguments,1).slice();ec(function(){a.apply(null,c)})}};function Ad(a){var b={},c={},d={},e="";try{var f=a.split("."),b=Pb(id(f[0])||""),c=Pb(id(f[1])||""),e=f[2],d=c.d||{};delete c.d}catch(g){}return{ph:b,Dc:c,data:d,bh:e}}function Bd(a){a=Ad(a).Dc;return"object"===typeof a&&a.hasOwnProperty("iat")?z(a,"iat"):null}function Cd(a){a=Ad(a);var b=a.Dc;return!!a.bh&&!!b&&"object"===typeof b&&b.hasOwnProperty("iat")};function Dd(a){this.Y=a;this.g=a.n.g}function Ed(a,b,c,d){var e=[],f=[];Na(b,function(b){"child_changed"===b.type&&a.g.Ad(b.Le,b.Ma)&&f.push(new H("child_moved",b.Ma,b.Ya))
10/02/16 4:36:05 PM
TypeError: Cannot set property '__lastUpdated' of null
    at __vue_ssr_bundle__:163:27
    at c (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:240:58)
    at /home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:201:710
    at ec (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:52:165)
    at ac (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:31:216)
    at bc (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:30:1259)
    at Object.I (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:218:393)
    at /home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:181:3
    at Rh.h.Jd (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:186:104)
    at Fh.Jd (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:176:364)
    at wh.Jg (/home/nowuser/src/node_modules/d6381efceed459a22e732f3ad18c37e173c3332c/lib/firebase-node.js:174:280)
10/02/16 4:36:05 PM
Error Error: Command cross-env NODE_ENV=production node server ended with code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
10/02/16 4:36:05 PM
(node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command cross-env NODE_ENV=production node server ended with code 1
```
</details>

**Comment by bomb1e** [comment]
Set up a temporary url here [https://vue2-hn.now.sh/](vue2-hn.now.sh)

**Comment by yyx990803** [comment]
fixed
