### ISSUE TITLE
error when npm run dev

### ISSUE THREAD

**Issue by broven** [vuejs/vue-hackernews-2.0#47]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev vue-hackernews-2.0@
6 info dev vue-hackernews-2.0@
7 verbose unsafe-perm in lifecycle true
8 info vue-hackernews-2.0@ Failed to exec dev script
9 verbose stack Error: vue-hackernews-2.0@ dev: `node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid vue-hackernews-2.0@
11 verbose cwd d:\pro\VUE\vue-hackernews-2.0
12 error Windows_NT 10.0.14393
13 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error vue-hackernews-2.0@ dev: `node server`
17 error Exit status 1
18 error Failed at the vue-hackernews-2.0@ dev script 'node server'.
18 error This is most likely a problem with the vue-hackernews-2.0 package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs vue-hackernews-2.0
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls vue-hackernews-2.0
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by pengfu** [comment]
node version should be 6+
