### ISSUE TITLE
can not use with vue-resource 1.0.3, `npm run dev` crash...

### ISSUE THREAD

**Issue by haycco** [vuejs/vue-hackernews-2.0#49]
Hi, guys!
I try to add vue-resource 1.0.3 to this sample. package.json.

```
"dependencies": {
    "es6-promise": "^3.2.1",
    "express": "^4.14.0",
    "firebase": "^2.4.2",
    "lru-cache": "^4.0.1",
    "serialize-javascript": "^1.3.0",
    "serve-favicon": "^2.3.0",
    "vue": "^2.0.1",
    "vue-router": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-server-renderer": "^2.0.1",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
  }
```

app.js

```
import VueResource from 'vue-resource'
Vue.use(VueResource)
```

But, when it run, throws error strack...

D:\vue-hackernews-2.0\server.js:85
    throw err
    ^

ReferenceError: document is not defined
    at Object.<anonymous> (D:\vue-hackernews-2.0\node_modules.1.0.3@vue-resource\dist\vue-resource.common.js:641:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (__vue_ssr_bundle__:2568:18)
    at **webpack_require** (**vue_ssr_bundle**:21:30)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\application\nodejs\node.exe" "D:\application\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ehr-web@ dev: `node server`

**Comment by cannap** [comment]
try axios or something similar this works on client & server

**Comment by tronghiep92** [comment]
Try install in client-entry.js

import Vue from 'vue';
import VueResource from 'vue-resource';
Vue.use(VueResource);
