### ISSUE TITLE
有koa2版本的吗？

### ISSUE THREAD

**Issue by JerroldLee** [vuejs/vue-hackernews-2.0#8]
有koa2版本的吗？

**Comment by yyx990803** [comment]
用 https://github.com/vkurchatkin/koa-connect 转一下 middleware 就行了

**Comment by JerroldLee** [comment]
仿照这个demo来加，加上去之后还是报错https://github.com/vkurchatkin/koa-connect/blob/master/examples/simple.js
```
TypeError: next is not a function
      at webpackDevMiddleware (/node_modules/webpack-dev-middleware/middleware.js:176:34)
      at dispatch (/node_modules/koa-compose/index.js:43:32)
      at next (/node_modules/koa-compose/index.js:44:18)
      at createGenerator (/node_modules/koa-convert/index.js:24:16)
      at next (native)
      at onFulfilled (/node_modules/co/index.js:65:19)
      at /node_modules/co/index.js:54:5
      at Object.co (/node_modules/co/index.js:50:10)
      at Object.toPromise (/node_modules/co/index.js:118:63)
      at next (/node_modules/co/index.js:99:29)

connect

  TypeError: next is not a function
      at webpackDevMiddleware (/node_modules/webpack-dev-middleware/middleware.js:176:34)
      at dispatch (/node_modules/koa-compose/index.js:43:32)
      at next (/node_modules/koa-compose/index.js:44:18)
      at createGenerator (/node_modules/koa-convert/index.js:24:16)
      at next (native)
      at onFulfilled (/node_modules/co/index.js:65:19)
      at /node_modules/co/index.js:54:5
      at Object.co (/node_modules/co/index.js:50:10)
      at Object.toPromise (/node_modules/co/index.js:118:63)
      at next (/node_modules/co/index.js:99:29)
```
